# Generated by Django 4.2.7 on 2023-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='a1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='a2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='a3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='a4',
            field=models.IntegerField(),
        ),
    ]
